### ISSUE TITLE
Firebase api not receiving auth change

### ISSUE THREAD

**Issue by egranville** [inouiw/capacitor-native-google-one-tap-signin#3]
I implemented the one tap signin, but it seems the firebase js api doesn't receive a notification when the user has signed in. 

I followed the example on your npm page and the plugin seems to work well and signs the user in but firebase doesn't seem to react to it. I decided to use the received idToken to turn it into a credential and feed that to firebase.auth. signInWithCredential. and that did work.

But when signing in a user that doesn't exist and they use the rendered button, the process takes place elsewhere and I can't get the result.

Is there something missing from the example to do this that might be trivial to everyone, but not to me?

**Comment by inouiw** [comment]
Hi @egranville,
I am happy that you are using the library. When starting with my app a few weeks ago, I first created the library because I could not find good alternatives.
About firebase. The library does not call firebase, but you should always get an idToken if the authentication succeeds.
The code is different if it runs in an andorid app, ios app or in the browser because I wanted to use the best experience for any platform.

When the button is rendered by calling `GoogleOneTapAuth.renderSignInButton` you will get a promise back. That promise will only return when authentication succeeds. The code is different for android, ios and web. For web the code is at https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/main/src/web.ts
For android the method `triggerGoogleSignIn` is called in https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/main/android/src/main/java/com/proventask/capacitor/GoogleOneTapAuth/GoogleOneTapAuth.java
For ios `triggerGoogleSignIn` is called in https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/main/ios/Plugin/Plugin.swift

I would first check if you see errors in the browser dev tools console.
Which platform are you using ios, android or web?
If you are using web, on which device, a computer or a phone?
I have not yet tested using the library in a browser on a phone. There might be some change needed there.

**Comment by egranville** [comment]
Hi @inouiw,

Thank you for your quick reaction and willingness to help!

I got the part about the render function returning a Promise and adapted my code accordingly and I'm happy to report it works like a charm! I also like very much how clean the API is (now that I get it).

I have one last question about the button that is generated, can I also specify an existing button for it to use?

**Comment by inouiw** [comment]
Hi @egranville,
about your question if it is possible to specify an existing button. For the web platform google renders the button in an iframe and it is not possible to modify the iframe content or to specify a own button. For android and ios there is no html button, so for android and ios I generate a button that looks almost the same as the google google generated button for web.
So it would only be possible to provide an own button for android and ios, however I would like to keep it as much consistent as possible for all platforms.
You can however modify the button appearance using the `gsiButtonConfiguration` parameter of the `renderSignInButton` method. Not all options are currently implemented for android and ios (because I create the button using custom html) but this can be changed easily.
David

**Comment by egranville** [comment]
Hi David,

Thanks, I will look into the gsiButtonConfiguration, as I'm only using it for Android at this moment.
Edward
