### ISSUE TITLE
Ios catch exception "The user canceled the sign-in flow"

### ISSUE THREAD

**Issue by gkielwasser** [inouiw/capacitor-native-google-one-tap-signin#6]
Hi,

When we click the rendered button on Ios, there is a permission popup asking if we allow granting access to "google.com". When we cancel the permission there is an exception I cannot managed to catch from javascript "The user canceled the sign-in flow".

I tryied surrounding GoogleOneTapAuth.renderSignInButon with catch block and also using the .then/.catch promises approach.

Do you have any clue about that ?

Thanks for great job!

**Comment by inouiw** [comment]
Hi @gkielwasser,
In the Safari developer console I can see the exception "Unhandled Promise Rejection: Error: The user canceled the sign-in flow." when I cancel the popup after clicking the button.
However I can click the button again and if I sign-in then the promise resolves successfully.
So to me the result seems correct but having a unhandled promise rejection shown in the console is not nice.

You cannot catch the exception because it is caused by a promise that runs within the promise you are waiting for. In this line: https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/8e50b819c68f2d67fa1297e25c6b81f8af227cc9/src/GoogleOneTapAuth.ts#L58

I will fix the code so there will be no more exception. It might take some days.

David

**Comment by inouiw** [comment]
One more thing, there was a related bug #4, please ensure you are using the latest version: 0.5.2

**Comment by gkielwasser** [comment]
> 

I confirm i'm using 0.5.2. I'm using Nextjs and in development it displays any unhandled error in an error popup to enforce having none. I suppose the exception will just be displayed in the console tab in a production environment.

It is also true button can still be clicked even after the unhandled exception.

Thank you for looking at handling this exception. Also it might be nice to be able to catch this error from javascript to perform any action when the user cancel (for instance warning him with a popup that he must accept to sign in with Google).

**Comment by inouiw** [comment]
@gkielwasser  I deployed a fix. Please check version 0.5.4.
When the user cancels there is currently no notification. For android and ios there is a cancel event that could be passed to the caller but for web I did not find a way (yet). So for consistency I did not add anything that would allow you to be notified when the user cancels the popup.
